controller_manager:
  ros__parameters:
    update_rate: 1000

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - base_to_shaft_arm
      - shaft_to_upper_arm
      - upper_arm_to_lower_arm